### ISSUE TITLE
Condition flowcard for thermostat_mode gives an error "mode is not defined"

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/apps-sdk-issues#173]
When checking a devices thermostat mode in the 'and' section of a flow it gives an error "mode is not defined".

![image](https://user-images.githubusercontent.com/2014478/108901855-ae930f80-761b-11eb-9875-91fb6c8999e4.png)

The device is added with the Virtual Devices app, using class 'thermostat' and capability 'thermostat_mode' (a.o.). 
The condition-flowcard is provided by the class/capability. There is no code for this in the VD-app.

![image](https://user-images.githubusercontent.com/2014478/108901949-c9658400-761b-11eb-9363-a47cd3a49c8a.png)

Also in the VD thermostat mode condition check card the inverting does not change the writing in the card. For example "Thermostat mode is"-text is the same when inverted, and it should be "Thermostat mode is not".

PS: SDK version is 2.

**Comment by jeroenwienk** [comment]
Found the issue will probably be fixed in the next Homey release.

**Comment by RobinBol** [comment]
@ArjanKranenburg Thanks for reporting this issue, we have implemented a fix in Homey v5.0.1, which is available as Experimental release. Could you verify that this update fixes the issue for you?

**Comment by ArjanKranenburg** [comment]
Thanks for the quick fix. This works OK with homeyVersion 5.0.1-rc.1.
However the inverting still does not change the writing in the card. For example "Thermostat mode is"-text is the same when inverted, and it should be "Thermostat mode is not".

**Comment by RobinBol** [comment]
Thanks, this should also be fixed in the next (patch) release!
