### ISSUE TITLE
TypeScript `device.ts` template for `homey app create driver` incorrect

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#261]
When creating a new driver using `homey app create driver` in a TS-based app, the generated `device.ts` has an invalid declaration for the `onSettings` method:
```
async onSettings({ oldSettings: {}, newSettings: {}, changedKeys: {} }): Promise<string|void>
```

It should be:
```
async onSettings(event = { oldSettings: {}, newSettings: {}, changedKeys: [] }): Promise<string|void>
```

**Comment by WeeJeWel** [comment]
Thank you for reporting! This is fixed in https://github.com/athombv/node-homey/commit/74e2bd5dcfcb5e9c02db76f0691cc984eb1b6fb6.

**Comment by robertklep** [comment]
It's still missing an actual argument name (`event = { ... }`).

**Comment by jeroenwienk** [comment]
> It's still missing an actual argument name (`event = { ... }`).

Are you sure it needs this at all? My TS knowledge is limited so and it compiles just fine?

**Comment by robertklep** [comment]
It compiles until you try to use any of `oldSettings`, `newSettings` or `changedKeys`, then it fails, but my suggestion doesn't fix it either.

This is actually a JS issue and no so much a TS issue, AFAIK you can't use explicit typing in destructured assignments and it just compiles to equivalent JS code.

Here's a shorter example of such JS code, which also fails because `foo` is not actually defined:
```
function test({ foo : {} }) {
  console.log('foo', foo);
}
test({ foo : 'bar' });
```

I think the correct way of declaring this with TS requires an interface in the type declaration:
```
// @types/homey/lib/Device.d.ts
interface OnSettingsArg {
  oldSettings : object;
  newSettings : object;
  changedKeys : string[];
}
declare class Device extends SimpleClass {
...
      onSettings(OnSettingsArg): Promise<string | void>;
}
```

And the implementation in `device.ts` should look like this: 
```
async onSettings({ oldSettings = {}, newSettings = {}, changedKeys = [] }): Promise<string|void> {
  this.log('MyDevice settings where changed');
}
```

**Comment by jeroenwienk** [comment]
> It compiles until you try to use any of `oldSettings`, `newSettings` or `changedKeys`, then it fails, but my suggestion doesn't fix it either.
> 
> This is actually a JS issue and no so much a TS issue, AFAIK you can't use explicit typing in destructured assignments and it just compiles to equivalent JS code.
> 
> Here's a shorter example of such JS code, which also fails because `foo` is not actually defined:
> 
> ```
> function test({ foo : {} }) {
>   console.log('foo', foo);
> }
> test({ foo : 'bar' });
> ```
> 
> I think the correct way of declaring this with TS requires an interface in the type declaration:
> 
> ```
> // @types/homey/lib/Device.d.ts
> interface OnSettingsArg {
>   oldSettings : object;
>   newSettings : object;
>   changedKeys : string[];
> }
> declare class Device extends SimpleClass {
> ...
>       onSettings(OnSettingsArg): Promise<string | void>;
> }
> ```
> 
> And the implementation in `device.ts` should look like this:
> 
> ```
> async onSettings({ oldSettings = {}, newSettings = {}, changedKeys = [] }): Promise<string|void> {
>   this.log('MyDevice settings where changed');
> }
> ```

I dont really time to fix it now but you can also create a PR here [https://github.com/athombv/node-homey-apps-sdk-v3-types](https://github.com/athombv/node-homey-apps-sdk-v3-types).

If you have time :wink:

**Comment by AlwinTS** [comment]
I agree with @robertklep. Is there a fix planned for this issue or a work around to get the newSettings in the method?

**Comment by RobinBol** [comment]
I believe this is the way to properly type `Device.onSettings()`:
- https://github.com/athombv/node-homey/pull/328
- https://github.com/athombv/node-homey-apps-sdk-v3-types/pull/17

**Comment by AlwinTS** [comment]
Thanks @RobinBol, tested and solved!
