### ISSUE TITLE
setCapabilityOptions fails to correctly set min

### ISSUE THREAD

**Issue by gslender** [athombv/apps-sdk-issues#348]
I'm seeing odd behaviour when setting the min dim value via setCapabilityOptions.

When using that, it seems to allow the lowest value to go negative when you slide down the minimum value. This is in the mobile iOS app. 

I'm doing this at device init after interogating the device to confirm what value it should be for min for a light dimmer.

**Comment by gslender** [comment]
For example... I'm seeing this after setting the min/max values and not sure if that's expected or if there is something I'm doing wrong in how this is supposed to work - any example that test/shows it working as designed??

![IMG_B24D6B444ABA-1](https://github.com/athombv/homey-apps-sdk-issues/assets/2344457/8362c002-0338-470a-87b4-5de9caa0e775)

**Comment by gslender** [comment]
This example is when the following code is set to the device...

`await _device.setCapabilityOptions("dim", { min: 0.04, max:1 });`

I would expect that this would set the slider to go between 4% and 100%... but I get this instead !??

![IMG_63C3F6D0DEFB-1](https://github.com/athombv/homey-apps-sdk-issues/assets/2344457/db21627c-1796-4147-b42e-3c412efe09da)

**Comment by regnerus** [comment]
Hi @gslender thanks for reporting this issue. We've recently made some changes to the slider component, could you verify if this is still an issue in te latest release 8.2.2?

**Comment by gslender** [comment]
These screenshots were using the latest TestFlight version 8.2.2 build 1502

**Comment by gslender** [comment]
Also, what's the expected behaviour in the web app?

**Comment by gslender** [comment]
Another unexpected bug (or perhaps lack of documentation) is that if you use code such as 

`await _device.setCapabilityOptions("dim", { min: 0.04 });`

You end up having other default values assigned (like 100 for max, step of 1 etc) which causes other problems. So the only fully correct way that you seem to be able to pass in the correct setCapabilityOptions is to provide the entire options of everything you anticipate might be needed to be set such as...

```
await _device.setCapabilityOptions("dim", {
            "min": 0.04,
            "max": 1,
            "decimals": 2,
            "step": 0.01,
            "opts": {
              "duration": true
            }
          });
```

**Comment by regnerus** [comment]
Thanks for reporting, I will try to reproduce in the mobile app.

**Comment by regnerus** [comment]
Hi @gslender,

Although not everything is listed in the changelog, most of the bugs you've reported should be resolved in release 8.3.1. https://homey.app/en-us/wiki/homey-mobile-app-changelog/

Thanks for your patience!

**Comment by gslender** [comment]
The slider in the iOS app is still broken and now other faults appear. Try this in any 
    "uiComponent": "slider" and watch the output in iOS mobile.

```
    "min": 2,
    "max": 22,
    "step": 1,
```

**Comment by regnerus** [comment]
Hi @gslender, I tried reproducing your issue on iOS but unfortunately I cant, see attached video.

https://github.com/user-attachments/assets/e4618285-320c-4bb3-8a44-1e8eaed4ce68

**Comment by gslender** [comment]
Well, if you've tested correct and cannot reproduce, close it, but I only reported it because I was seeing a serious behaviour bug. This was on the TestFlight release at the time, and given I cannot recall which it was, perhaps it was resolved !?
