### ISSUE TITLE
BLE discovery doesn't give `live` results.

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#6]
I've tested by app `beacon` on v2.0.0. This app does a discovery of BLE beacons and check if the added devices are in that list to check if they are in/out range.

What do i expect:
`Homey.ManagerBLE.discover` gives a list of BleDevices that are in range.

What is the result:
`Homey.ManagerBLE.discover` gives a list of BleDevices that are not in range anymore, but where the first time the function ran.

It looks like a cache related issue.

**Comment by Swiftnesses** [comment]
I wondered why my devices stayed connected!

**Comment by koktaildotcom** [comment]
Still an issue with rc4

**Comment by koktaildotcom** [comment]
Still an issue with rc7

**Comment by zwaardemaker** [comment]
Still an issue with rc8 and 9. Would be great if this issue will be resolved soon ;-)

**Comment by rvmuilekom69** [comment]
Indeed, eagerly waiting when this Will be resolved

**Comment by koktaildotcom** [comment]
@WeeJeWel any idea when you can take a look at this issue?

**Comment by rvmuilekom69** [comment]
I think this issue is solved in firmware rc11, or is this another problem?

**Comment by koktaildotcom** [comment]
This issue still exist on rc11

**Comment by notabene00** [comment]
Yep, same here

**Comment by notabene00** [comment]
rc12, still the same behaviour

**Comment by zwaardemaker** [comment]
Very annoying! Not much magic behind this

**Comment by zwaardemaker** [comment]
RC13, still the same behaviour

**Comment by koktaildotcom** [comment]
Still an issue with 2.0.0

**Comment by rvmuilekom69** [comment]
I am not going to update if this does not get fixed 😕

**Comment by zwaardemaker** [comment]
@WeeJeWel will athom look at this issue?

**Comment by WeeJeWel** [comment]
Yes. All BLE issues: We will address this issue in a 2.x release. Sorry for the delay!

**Comment by rvmuilekom69** [comment]
So waiting until 2020 before upgrade to version 2.x?

**Comment by WeeJeWel** [comment]
By 2020 v2.x is definitely available.

**Comment by rvmuilekom69** [comment]
I know you/athom probably have more pressing issues to solve, but is this one of the more high priority issues or does it have a low(er) priority?
Thanks 😉

**Comment by zwaardemaker** [comment]
high priority!

**Comment by Eternity-again** [comment]
Bump :-)

**Comment by Shadowz7** [comment]
beacon is the best presence app, please fast!

**Comment by mrquincle** [comment]
Required for Crownstone (https://github.com/crownstone/crownstone-homey) as well.

**Comment by mrquincle** [comment]
Do you have Crownstones at Homey? We can send a few samples if this would make the debugging process of BLE faster.

**Comment by bvdbos** [comment]
> It looks like a cache related issue.

Couldn't this just be a typo in creating an array ?

**Comment by wzhick** [comment]
still not work

**Comment by WeeJeWel** [comment]
Fixed in Homey v2.0.5. BLE discover results now expire after 45s.

**Comment by notabene00** [comment]
What am I doing wrong?
Still the same behaviour. 
I have code like this:
```js
Homey.ManagerBLE.discover().then(advertisementsArray => {
    let advertisement = advertisementsArray.first(advertisement => {
        return this.devices.hasOwnProperty(advertisement.uuid)
    })
    if (advertisement) {
        this.updateCapabilities(advertisement)
    }
})
```
But the `serviceData` attribute of `advertisement` is the same data every single time.
Explanation: I'm developing app for Mijia Hygrothermographs, which sends data to every thing around 'em. There are battery, humidity and temperature data in this serviceData. And it was working till 2.0.
