### ISSUE TITLE
Appstore Markdown is not correctly displayed

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/apps-sdk-issues#68]
As far as i can tell, the Markdown file is not correctly handled in the App store, are there any Guidelines to make it look good for the Appstore (maybe seperatly)?
I've saw that i can greate a special file styled as Markdown to be visible in the Appstore that has other Content then in the GitHub README, but the Interpreting doesn't change.

Here is a Screeshot of the GitHub Version (fully styled and also full Text is visible):
![bildschirmfoto 2019-02-26 um 15 34 29](https://user-images.githubusercontent.com/28244954/53420623-69ac5200-39dc-11e9-98e3-ed417b1e55b5.png)

Here you find the exact same File interpreted by the Athom App store(missing the last line!):
![bildschirmfoto 2019-02-26 um 15 33 47](https://user-images.githubusercontent.com/28244954/53420691-85175d00-39dc-11e9-9674-e424b838eea2.png)
![bildschirmfoto 2019-02-26 um 15 33 56](https://user-images.githubusercontent.com/28244954/53420698-88124d80-39dc-11e9-8638-99733db307b4.png)

**Comment by WeeJeWel** [comment]
Could you link to the app store page where this goes wrong?

**Comment by carp3-noctem** [comment]
It is this Link (alpha Version of the App):
https://apps.athom.com/app/eu.carp3-noctem.enigma2
link to github:
https://github.com/carp3-noctem/eu.carp3-noctem.enigma2

**Comment by WeeJeWel** [comment]
Fixed, thank you for reporting!

**Comment by carp3-noctem** [comment]
@WeeJeWel Nearly...
The last line of the original file is still missing, the Markdown indeed now is correctly interpreted.
Sorry :-)

**Comment by WeeJeWel** [comment]
![screen shot 2019-02-28 at 15 41 31](https://user-images.githubusercontent.com/319873/53574179-54b3f800-3b6f-11e9-91bf-d830adc1e019.png)

It's shown correct here. Which browser?

**Comment by carp3-noctem** [comment]
Firefox 65.0.1 (64-Bit) used on Mac OSX 10.14.3
If i copy and Paste the last lines, everything is there, so it seems an issue with the scroll ending to early.

**Comment by carp3-noctem** [comment]
@WeeJeWel I've redone the Markdown to a (in my eyes) better look, there are still some "features" missing. Is it possible to build them into your Appstore, or should i do an extra Appstore file?
If you check the current Version 0.0.6 and the display in the App Store, the Markdown Task List is wrongly interpreted.

**Comment by carp3-noctem** [comment]
@WeeJeWel any Updates for this topic?

**Comment by daneedk** [comment]
@WeeJeWel please see this one too: 
https://github.com/athombv/homey/issues/2055

**Comment by WeeJeWel** [comment]
Don't count on the extra features being added anytime soon.

**Comment by carp3-noctem** [comment]
OK, thanks for the Update. Then I will go ahead and make a Appstore file so it will look nice.

**Comment by WeeJeWel** [comment]
Closing this because most features are github-only and not standardised.
